// <auto-generated />
using System;
using Domains.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domains.Migrations
{
    [DbContext(typeof(BackendDBContext))]
    [Migration("20230626023914_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Chinese_Taiwan_Stroke_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Domains.Models.AccountPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableCheckPasswordAge")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLoginFailDetection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePasswordHistory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoginFailMaxTimes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoginFailTimesLockMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumPasswordLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PasswordAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PasswordComplexity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PasswordHistory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccountPolicy");
                });

            modelBuilder.Entity("Domains.Models.ExceptionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallStack")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExceptionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MyUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OSType")
                        .HasColumnType("TEXT");

                    b.Property<string>("OSVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MyUserId");

                    b.ToTable("ExceptionRecord");
                });

            modelBuilder.Entity("Domains.Models.MailQueue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SendTimes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SendedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("MailQueue");
                });

            modelBuilder.Entity("Domains.Models.MenuData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForceLoad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuRoleId");

                    b.ToTable("MenuData");
                });

            modelBuilder.Entity("Domains.Models.MenuRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuRole");
                });

            modelBuilder.Entity("Domains.Models.MyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ForceChangePasswordDatetime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ForceLogoutDatetime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginDatetime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoginFailTimes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoginFailUnlockDatetime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuRoleId");

                    b.ToTable("MyUser");
                });

            modelBuilder.Entity("Domains.Models.MyUserPasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangePasswordDatetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .HasColumnType("TEXT");

                    b.Property<int>("MyUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MyUserId");

                    b.ToTable("MyUserPasswordHistory");
                });

            modelBuilder.Entity("Domains.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ListPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderMasterId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Domains.Models.OrderMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OrderMaster");
                });

            modelBuilder.Entity("Domains.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ListPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<short>("ModelYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Domains.Models.SystemLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updatetime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemLog");
                });

            modelBuilder.Entity("EntityModel.Entities.ExpertDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConvertPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExpertDirectory");
                });

            modelBuilder.Entity("EntityModel.Entities.ExpertFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConvertDirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpertDirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProcessChunk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpertDirectoryId");

                    b.ToTable("ExpertFile");
                });

            modelBuilder.Entity("EntityModel.Entities.ExpertFileChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConvertIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpertFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpertFileId");

                    b.ToTable("ExpertFileChunk");
                });

            modelBuilder.Entity("Domains.Models.ExceptionRecord", b =>
                {
                    b.HasOne("Domains.Models.MyUser", "MyUser")
                        .WithMany()
                        .HasForeignKey("MyUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MyUser");
                });

            modelBuilder.Entity("Domains.Models.MenuData", b =>
                {
                    b.HasOne("Domains.Models.MenuRole", "MenuRole")
                        .WithMany("MenuData")
                        .HasForeignKey("MenuRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuRole");
                });

            modelBuilder.Entity("Domains.Models.MyUser", b =>
                {
                    b.HasOne("Domains.Models.MenuRole", "MenuRole")
                        .WithMany()
                        .HasForeignKey("MenuRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuRole");
                });

            modelBuilder.Entity("Domains.Models.MyUserPasswordHistory", b =>
                {
                    b.HasOne("Domains.Models.MyUser", "MyUser")
                        .WithMany("MyUserPasswordHistory")
                        .HasForeignKey("MyUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MyUser");
                });

            modelBuilder.Entity("Domains.Models.OrderItem", b =>
                {
                    b.HasOne("Domains.Models.OrderMaster", "OrderMaster")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderMaster");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityModel.Entities.ExpertFile", b =>
                {
                    b.HasOne("EntityModel.Entities.ExpertDirectory", "ExpertDirectory")
                        .WithMany()
                        .HasForeignKey("ExpertDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpertDirectory");
                });

            modelBuilder.Entity("EntityModel.Entities.ExpertFileChunk", b =>
                {
                    b.HasOne("EntityModel.Entities.ExpertFile", "ExpertFile")
                        .WithMany()
                        .HasForeignKey("ExpertFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpertFile");
                });

            modelBuilder.Entity("Domains.Models.MenuRole", b =>
                {
                    b.Navigation("MenuData");
                });

            modelBuilder.Entity("Domains.Models.MyUser", b =>
                {
                    b.Navigation("MyUserPasswordHistory");
                });

            modelBuilder.Entity("Domains.Models.OrderMaster", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domains.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
